name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: unibuc-cs/software-engineering-product-olimpicii/Library
          key: Library-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Ensure Directory Exists
        run: |
          if [ ! -d "unibuc-cs/software-engineering-product-olimpicii" ]; then
            echo "Directory does not exist. Cloning repository..."
            git clone https://github.com/unibuc-cs/software-engineering-product-olimpicii.git unibuc-cs/software-engineering-product-olimpicii
          fi

      - name: Navigate to Project Directory
        working-directory: unibuc-cs/software-engineering-product-olimpicii
        run: |
          echo "Current directory: $(pwd)"
          git rev-parse --is-shallow-repository

      - name: Install Dependencies
        working-directory: unibuc-cs/software-engineering-product-olimpicii
        run: |
          npm install || yarn install  # În funcție de managerul de pachete folosit

      - name: Run Tests
        working-directory: unibuc-cs/software-engineering-product-olimpicii
        run: npm test || yarn test

      - name: Build Project
        working-directory: unibuc-cs/software-engineering-product-olimpicii
        run: npm run build || yarn build

      - name: Activate Unity License
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: 2021.3.0f1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Build with Unity
        uses: game-ci/unity-builder@v2
        with:
          projectPath: unibuc-cs/software-engineering-product-olimpicii
          unityVersion: 2021.3.0f1
          targetPlatform: StandaloneWindows64

      - name: Deactivate Unity License
        if: always()
        uses: game-ci/unity-return-license@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
